apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-app
  namespace: gitops
  labels:
    app: flask
    project: gitops-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask
        project: gitops-demo

    spec:
      containers:
        - name: flask

          image: sujith0227/gitops-flask-app:v1.0.0

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: flask-config

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 20
            periodSeconds: 10
